version: '3'

services:
  my-postgres:
    container_name: my-postgres
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data:rw
    networks:
      - my-network

  my-pgadmin:
    container_name: my-pgadmin
    image: dpage/pgadmin4
    ports:
      - "15432:80"

    # PARA TER ACESSO AO PGADMIN, SETAR AS CREDENCIAIS
    # environment:
    #   - PGADMIN_DEFAULT_EMAIL=
    #   - PGADMIN_DEFAULT_PASSWORD=
    networks:
      - my-network

networks:
  my-network:
    name: my-network
    driver: bridge

volumes:
  postgres-volume:
